import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileText, FileUp, Sparkles, AlertCircle, RefreshCw, BrainCircuit, Shield } from "lucide-react";
import { useDetectText, useDetectFile } from "@workspace/api-client-react";
import { ScoreGauge } from "@/components/ScoreGauge";
import { VerdictBadge } from "@/components/VerdictBadge";
import { FileDropzone } from "@/components/FileDropzone";
import { clsx } from "clsx";

type Tab = "text" | "file";

export default function Home() {
  const [activeTab, setActiveTab] = useState<Tab>("text");
  const [textInput, setTextInput] = useState("");
  const [selectedFile, setSelectedFile] = useState<File | null>(null);

  const detectTextMutation = useDetectText();
  const detectFileMutation = useDetectFile();

  const handleDetectText = () => {
    if (textInput.trim().length < 10) return;
    detectTextMutation.mutate({ data: { text: textInput } });
  };

  const handleDetectFile = () => {
    if (!selectedFile) return;
    detectFileMutation.mutate({ data: { file: selectedFile } });
  };

  const isLoading = detectTextMutation.isPending || detectFileMutation.isPending;
  const result = activeTab === "text" ? detectTextMutation.data : detectFileMutation.data;
  const error = activeTab === "text" ? detectTextMutation.error : detectFileMutation.error;

  const handleReset = () => {
    if (activeTab === "text") {
      setTextInput("");
      detectTextMutation.reset();
    } else {
      setSelectedFile(null);
      detectFileMutation.reset();
    }
  };

  return (
    <div className="dark min-h-screen w-full bg-background relative overflow-hidden flex flex-col">
      {/* Decorative Background */}
      <div className="absolute inset-0 z-0 pointer-events-none overflow-hidden">
        <div className="absolute top-[-20%] left-[-10%] w-[60%] h-[60%] rounded-full bg-primary/8 blur-[140px]" />
        <div className="absolute bottom-[-20%] right-[-10%] w-[60%] h-[60%] rounded-full bg-accent/8 blur-[140px]" />
      </div>

      {/* Header */}
      <header className="relative z-10 w-full border-b border-border/50 bg-background/80 backdrop-blur-md sticky top-0">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5 text-primary">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center shadow-md shadow-primary/30">
              <Shield className="w-4 h-4 text-primary-foreground" />
            </div>
            <span className="font-bold text-xl tracking-tight text-foreground">
              AI <span className="text-primary">Detector</span>
            </span>
          </div>
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground bg-muted/60 px-3 py-1.5 rounded-full border border-border/50">
            <div className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
            Shakies
          </div>
        </div>
      </header>

      <main className="flex-1 relative z-10 w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 lg:py-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 items-start">

          {/* LEFT COLUMN: INPUT */}
          <div className="lg:col-span-5 flex flex-col gap-6">
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2 mb-1">
                <Sparkles className="w-5 h-5 text-primary" />
                <span className="text-sm font-medium text-primary uppercase tracking-wider">Content Analysis</span>
              </div>
              <h1 className="text-3xl sm:text-4xl font-extrabold text-foreground tracking-tight leading-tight">
                Detect AI-Generated<br />
                <span className="text-primary">Content Instantly</span>
              </h1>
              <p className="text-muted-foreground text-base mt-1">
                Analyze text, documents, and images to determine whether they were written by a human or generated by AI.
              </p>
            </div>

            {/* Supported types */}
            <div className="grid grid-cols-3 gap-3">
              {[
                { label: "Text", icon: "📝" },
                { label: "PDF & Word", icon: "📄" },
                { label: "Images", icon: "🖼️" },
              ].map((item) => (
                <div key={item.label} className="flex flex-col items-center gap-1.5 p-3 rounded-xl bg-card border border-border/60 shadow-sm text-center">
                  <span className="text-xl">{item.icon}</span>
                  <span className="text-xs font-medium text-muted-foreground">{item.label}</span>
                </div>
              ))}
            </div>

            {/* Input Panel */}
            <div className="bg-card rounded-2xl overflow-hidden border border-border shadow-sm">
              {/* Tabs */}
              <div className="flex border-b border-border">
                <button
                  onClick={() => setActiveTab("text")}
                  className={clsx(
                    "flex-1 flex items-center justify-center gap-2 py-3.5 px-4 text-sm font-semibold transition-all relative",
                    activeTab === "text" ? "text-primary bg-primary/5" : "text-muted-foreground hover:text-foreground hover:bg-muted/30"
                  )}
                >
                  <FileText className="w-4 h-4" />
                  Text Input
                  {activeTab === "text" && (
                    <motion.div layoutId="activeTab" className="absolute bottom-0 left-0 right-0 h-0.5 bg-primary" />
                  )}
                </button>
                <button
                  onClick={() => setActiveTab("file")}
                  className={clsx(
                    "flex-1 flex items-center justify-center gap-2 py-3.5 px-4 text-sm font-semibold transition-all relative",
                    activeTab === "file" ? "text-primary bg-primary/5" : "text-muted-foreground hover:text-foreground hover:bg-muted/30"
                  )}
                >
                  <FileUp className="w-4 h-4" />
                  File Upload
                  {activeTab === "file" && (
                    <motion.div layoutId="activeTab" className="absolute bottom-0 left-0 right-0 h-0.5 bg-primary" />
                  )}
                </button>
              </div>

              <div className="p-5">
                <AnimatePresence mode="wait">
                  {activeTab === "text" ? (
                    <motion.div
                      key="text"
                      initial={{ opacity: 0, x: -10 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: 10 }}
                      className="flex flex-col gap-4"
                    >
                      <textarea
                        value={textInput}
                        onChange={(e) => setTextInput(e.target.value)}
                        placeholder="Paste your text here to analyze... (minimum 10 characters)"
                        className="w-full h-52 p-4 rounded-xl border border-border bg-background/60 text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/40 focus:border-primary transition-all resize-none text-sm leading-relaxed"
                        disabled={isLoading}
                      />
                      <div className="flex justify-between items-center">
                        <span className="text-xs text-muted-foreground">
                          {textInput.length} characters
                        </span>
                        <button
                          onClick={handleDetectText}
                          disabled={textInput.trim().length < 10 || isLoading}
                          className="px-5 py-2.5 rounded-xl font-semibold bg-primary text-primary-foreground shadow-md shadow-primary/20 hover:shadow-lg hover:shadow-primary/30 hover:-translate-y-0.5 active:translate-y-0 disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none transition-all text-sm"
                        >
                          {isLoading ? "Analyzing..." : "Analyze Text"}
                        </button>
                      </div>
                    </motion.div>
                  ) : (
                    <motion.div
                      key="file"
                      initial={{ opacity: 0, x: 10 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: -10 }}
                      className="flex flex-col gap-4"
                    >
                      <FileDropzone
                        file={selectedFile}
                        onFileSelect={setSelectedFile}
                        isLoading={isLoading}
                      />
                      <div className="flex justify-end mt-1">
                        <button
                          onClick={handleDetectFile}
                          disabled={!selectedFile || isLoading}
                          className="px-5 py-2.5 rounded-xl font-semibold bg-primary text-primary-foreground shadow-md shadow-primary/20 hover:shadow-lg hover:shadow-primary/30 hover:-translate-y-0.5 active:translate-y-0 disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none transition-all text-sm"
                        >
                          {isLoading ? "Analyzing..." : "Analyze File"}
                        </button>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </div>

            {/* Footer hints */}
            <div className="flex flex-col gap-1.5 text-xs text-muted-foreground/60">
              <p>✓ Supports: Text · PDF · Word · Images</p>
              <p>✓ AGI</p>
            </div>
          </div>

          {/* RIGHT COLUMN: RESULTS */}
          <div className="lg:col-span-7 flex flex-col h-full">
            <AnimatePresence mode="wait">
              {isLoading ? (
                <motion.div
                  key="loading"
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  className="bg-card border border-border rounded-3xl p-12 flex flex-col items-center justify-center min-h-[500px] shadow-sm"
                >
                  <div className="relative mb-8">
                    <div className="w-20 h-20 border-4 border-primary/20 border-t-primary rounded-full animate-spin" />
                    <div className="absolute inset-0 flex items-center justify-center">
                      <BrainCircuit className="w-7 h-7 text-primary/60" />
                    </div>
                  </div>
                  <h3 className="text-xl font-bold text-foreground mb-2">Analyzing Content...</h3>
                  <p className="text-muted-foreground text-center max-w-sm text-sm leading-relaxed">
                    Our AI is scanning patterns, semantics, and linguistic structures of the content
                  </p>
                </motion.div>
              ) : error ? (
                <motion.div
                  key="error"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="bg-card border border-destructive/20 rounded-3xl p-8 flex flex-col items-center justify-center min-h-[500px] text-center shadow-sm"
                >
                  <div className="w-16 h-16 rounded-full bg-destructive/10 flex items-center justify-center mb-4">
                    <AlertCircle className="w-8 h-8 text-destructive" />
                  </div>
                  <h3 className="text-xl font-bold text-foreground mb-2">Analysis Failed</h3>
                  <p className="text-muted-foreground text-sm max-w-sm">
                    {(error as any)?.message || "An unexpected error occurred while analyzing the content. Please try again."}
                  </p>
                  <button onClick={handleReset} className="mt-6 px-5 py-2 rounded-lg bg-secondary text-secondary-foreground hover:bg-secondary/80 transition-colors text-sm font-medium">
                    Try Again
                  </button>
                </motion.div>
              ) : result ? (
                <motion.div
                  key="result"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="bg-card border border-border rounded-3xl p-6 sm:p-8 flex flex-col gap-6 shadow-sm relative overflow-hidden"
                >
                  {/* Reset button */}
                  <div className="absolute top-5 right-5 z-20">
                    <button
                      onClick={handleReset}
                      className="p-2 rounded-full bg-secondary text-muted-foreground hover:text-foreground hover:bg-secondary/80 transition-colors group"
                      title="New Analysis"
                    >
                      <RefreshCw className="w-4 h-4 group-hover:rotate-180 transition-transform duration-500" />
                    </button>
                  </div>

                  {/* Top: verdict + gauge */}
                  <div className="flex flex-col sm:flex-row items-center sm:items-start gap-6 justify-between">
                    <div className="flex flex-col gap-4 flex-1 text-center sm:text-left">
                      <div>
                        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-2">Analysis Result</p>
                        <h2 className="text-2xl font-bold text-foreground mb-4">Analysis Complete</h2>
                        <VerdictBadge verdict={result.verdict as any} className="sm:origin-left" />
                      </div>

                      <div className="bg-background rounded-2xl p-4 border border-border/60">
                        <h4 className="text-xs font-bold text-foreground uppercase tracking-wider mb-2">Explanation</h4>
                        <p className="text-muted-foreground leading-relaxed text-sm">
                          {result.explanation}
                        </p>
                      </div>
                    </div>

                    <div className="flex-shrink-0">
                      <ScoreGauge score={result.score} size={170} strokeWidth={13} />
                    </div>
                  </div>

                  <div className="w-full h-px bg-border/60" />

                  {/* Indicators */}
                  <div>
                    <h4 className="text-xs font-bold text-foreground uppercase tracking-wider mb-3 flex items-center gap-2">
                      <Sparkles className="w-3.5 h-3.5 text-primary" />
                      Key Indicators
                    </h4>
                    <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                      {result.highlights.map((highlight, idx) => (
                        <motion.li
                          key={idx}
                          initial={{ opacity: 0, x: -10 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: 0.2 + (idx * 0.08) }}
                          className="flex items-start gap-2.5 bg-secondary/40 p-3 rounded-xl border border-border/40"
                        >
                          <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                          <span className="text-sm text-foreground/90 leading-relaxed">{highlight}</span>
                        </motion.li>
                      ))}
                    </ul>
                  </div>

                  {/* Extracted text preview */}
                  {result.extractedText && (
                    <div>
                      <h4 className="text-xs font-bold text-foreground uppercase tracking-wider mb-2">Extracted Content Preview</h4>
                      <div className="bg-background rounded-xl p-4 border border-border/50 h-28 overflow-y-auto text-xs text-muted-foreground leading-relaxed font-mono">
                        {result.extractedText}
                      </div>
                    </div>
                  )}

                  {/* File info */}
                  {result.fileType && result.fileType !== "text" && (
                    <div className="flex items-center gap-2 text-xs text-muted-foreground bg-muted/40 px-3 py-2 rounded-lg">
                      <span>File Type:</span>
                      <span className="font-medium text-foreground uppercase">{result.fileType}</span>
                    </div>
                  )}
                </motion.div>
              ) : (
                <motion.div
                  key="empty"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="bg-card border border-dashed border-border rounded-3xl p-12 flex flex-col items-center justify-center min-h-[500px]"
                >
                  <div className="w-24 h-24 mb-6 rounded-full bg-primary/8 flex items-center justify-center">
                    <BrainCircuit className="w-11 h-11 text-primary/50" />
                  </div>
                  <h3 className="text-xl font-bold text-foreground mb-2">Awaiting Input</h3>
                  <p className="text-muted-foreground text-center max-w-xs text-sm leading-relaxed">
                    Enter text or upload a file to get a detailed analysis of whether the content was AI-generated.
                  </p>
                  <div className="mt-8 flex flex-col gap-2 text-xs text-muted-foreground/60 text-center">
                    <p>✓ Supports: Text · PDF · Word · Images</p>
                    <p>✓ AGI</p>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </main>
    </div>
  );
}
