import { Router, type IRouter, type Request, type Response } from "express";
import multer from "multer";
import mammoth from "mammoth";
import pdfParse from "pdf-parse/lib/pdf-parse.js";
import OpenAI from "openai";
import { DetectTextBody, DetectTextResponse, DetectFileResponse } from "@workspace/api-zod";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const router: IRouter = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 20 * 1024 * 1024 } });

const DETECTION_SYSTEM_PROMPT = `You are an expert AI content detector. Your task is to analyze text and determine the probability that it was written by an AI (like ChatGPT, Claude, Gemini, etc.) vs a human.

Analyze the text for:
- Repetitive sentence structures
- Overly formal or neutral tone
- Lack of personal anecdotes or specific details
- Excessive use of transitional phrases ("Furthermore", "Moreover", "In conclusion")
- Perfect grammar with no colloquialisms
- Generic and non-specific content
- Unnaturally balanced paragraph lengths
- Missing idiomatic expressions or cultural nuances

Return ONLY a JSON object (no markdown, no explanation outside the JSON) with this exact structure:
{
  "score": <number 0-100 where 0=definitely human and 100=definitely AI>,
  "verdict": <one of: "human", "likely_human", "uncertain", "likely_ai", "ai">,
  "explanation": <2-3 sentence explanation of your analysis>,
  "highlights": <array of 3-5 specific indicators you found>
}

Verdict scale:
- 0-20: "human"
- 21-40: "likely_human"
- 41-60: "uncertain"
- 61-80: "likely_ai"
- 81-100: "ai"`;

async function analyzeWithAI(text: string): Promise<{
  score: number;
  verdict: string;
  explanation: string;
  highlights: string[];
}> {
  const truncatedText = text.slice(0, 6000);

  const response = await openai.chat.completions.create({
    model: "gpt-5.2",
    max_completion_tokens: 8192,
    messages: [
      { role: "system", content: DETECTION_SYSTEM_PROMPT },
      {
        role: "user",
        content: `Analyze this text:\n\n${truncatedText}`,
      },
    ],
  });

  const content = response.choices[0]?.message?.content ?? "{}";
  const cleaned = content.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
  const parsed = JSON.parse(cleaned);

  return {
    score: Math.max(0, Math.min(100, Number(parsed.score) || 50)),
    verdict: parsed.verdict || "uncertain",
    explanation: parsed.explanation || "Unable to analyze",
    highlights: Array.isArray(parsed.highlights) ? parsed.highlights : [],
  };
}

async function analyzeImageWithAI(imageBuffer: Buffer, mimeType: string): Promise<{
  score: number;
  verdict: string;
  explanation: string;
  highlights: string[];
}> {
  const base64 = imageBuffer.toString("base64");
  const dataUrl = `data:${mimeType};base64,${base64}`;

  const response = await openai.chat.completions.create({
    model: "gpt-5.2",
    max_completion_tokens: 8192,
    messages: [
      {
        role: "system",
        content: `You are an expert AI image detector. Analyze the provided image and determine the probability it was generated by AI (DALL-E, Midjourney, Stable Diffusion, etc.) vs taken by a real camera or drawn by a human.

Look for:
- Unnatural skin textures, hair, or fingers
- Inconsistent lighting or shadows
- Dreamlike or surreal quality
- Perfect symmetry or overly smooth surfaces
- Artifacts or distortions
- Unrealistic backgrounds or environments
- Missing or extra body parts

Return ONLY a JSON object with this structure:
{
  "score": <0-100>,
  "verdict": <"human", "likely_human", "uncertain", "likely_ai", or "ai">,
  "explanation": <2-3 sentences>,
  "highlights": [<3-5 specific visual indicators>]
}`,
      },
      {
        role: "user",
        content: [
          {
            type: "image_url",
            image_url: { url: dataUrl },
          } as { type: "image_url"; image_url: { url: string } },
        ],
      },
    ],
  });

  const content = response.choices[0]?.message?.content ?? "{}";
  const cleaned = content.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
  const parsed = JSON.parse(cleaned);

  return {
    score: Math.max(0, Math.min(100, Number(parsed.score) || 50)),
    verdict: parsed.verdict || "uncertain",
    explanation: parsed.explanation || "Unable to analyze",
    highlights: Array.isArray(parsed.highlights) ? parsed.highlights : [],
  };
}

router.post("/detect/text", async (req: Request, res: Response) => {
  try {
    const parsed = DetectTextBody.safeParse(req.body);
    if (!parsed.success) {
      res.status(400).json({ error: "validation_error", message: "Text must be at least 10 characters" });
      return;
    }

    const { text } = parsed.data;
    const analysis = await analyzeWithAI(text);

    const result = DetectTextResponse.parse({
      ...analysis,
      fileType: "text",
    });

    res.json(result);
  } catch (err) {
    console.error("Text detection error:", err);
    res.status(500).json({ error: "server_error", message: "Failed to analyze text" });
  }
});

router.post("/detect/file", upload.single("file"), async (req: Request, res: Response) => {
  try {
    if (!req.file) {
      res.status(400).json({ error: "validation_error", message: "No file uploaded" });
      return;
    }

    const { originalname, mimetype, buffer } = req.file;
    const ext = originalname.split(".").pop()?.toLowerCase();

    let extractedText = "";
    let fileType = "unknown";
    let isImage = false;
    let imageMime = mimetype;

    if (ext === "pdf" || mimetype === "application/pdf") {
      fileType = "pdf";
      const data = await pdfParse(buffer);
      extractedText = data.text;
    } else if (ext === "docx" || mimetype === "application/vnd.openxmlformats-officedocument.wordprocessingml.document") {
      fileType = "word";
      const result = await mammoth.extractRawText({ buffer });
      extractedText = result.value;
    } else if (["png", "jpg", "jpeg", "gif", "webp"].includes(ext ?? "") || mimetype.startsWith("image/")) {
      fileType = "image";
      isImage = true;
      imageMime = mimetype || `image/${ext}`;
    } else {
      res.status(400).json({ error: "unsupported_format", message: "Unsupported file type. Please upload PDF, Word (.docx), or image files." });
      return;
    }

    let analysis;
    if (isImage) {
      analysis = await analyzeImageWithAI(buffer, imageMime);
    } else {
      if (!extractedText || extractedText.trim().length < 10) {
        res.status(400).json({ error: "empty_content", message: "Could not extract meaningful text from the file" });
        return;
      }
      analysis = await analyzeWithAI(extractedText);
    }

    const result = DetectFileResponse.parse({
      ...analysis,
      fileType,
      extractedText: extractedText ? extractedText.slice(0, 500) + (extractedText.length > 500 ? "..." : "") : undefined,
    });

    res.json(result);
  } catch (err) {
    console.error("File detection error:", err);
    res.status(500).json({ error: "server_error", message: "Failed to analyze file" });
  }
});

export default router;
